FROM node:18.20.4-alpine3.19

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG PORT=3000
ARG ECOSYSTEM=portal
ENV ECOSYSTEM=${ECOSYSTEM}

EXPOSE ${PORT}

RUN addgroup -g ${GROUP_ID} portal && \
    adduser -u ${USER_ID} -G portal -s /bin/sh -D portal

WORKDIR /app

COPY package*.json .

RUN npm i pm2 -g

COPY . .

RUN chown -R portal:portal /app

USER portal

RUN npm i

RUN if [ -d "/app/assets/${ECOSYSTEM}" ]; then \
        ln -s /app/assets/${ECOSYSTEM} /app/assets/static; \
    elif [ -d "/app/assets/default" ]; then \
        ln -s /app/assets/default /app/assets/static; \
    else \
        echo "Error: Neither ${ECOSYSTEM} nor default assets directory exists" && exit 1; \
    fi

CMD pm2-runtime start ecosystem.config.js --env ${ECOSYSTEM}
