services:
  portal:
    container_name: portal
    build:
      context: .
      dockerfile: Dockerfile.ita
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    expose:
      - "3001"
    networks:
      - netlab01
    volumes:
      - $PWD/config:/portal/site01/config
      - portaldata:/app/assets/static/core/uploads

volumes:
  portaldata:
    name: portaldata
    external: true

networks:
  netlab01:
    external: true
