FROM node:18.20.4-alpine3.19

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG PORT=3000
ARG ECOSYSTEM=portal
ENV ECOSYSTEM=${ECOSYSTEM}
ENV TZ=America/Sao_Paulo

EXPOSE ${PORT}

RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo "${TZ}" > /etc/timezone && \
    addgroup -g ${GROUP_ID} portal && \
    adduser -u ${USER_ID} -G portal -s /bin/sh -D portal

WORKDIR /app

COPY package*.json .

RUN npm i pm2 -g

COPY . .

RUN chown -R portal:portal /app

USER portal

RUN npm i

RUN cp -r /app/assets/default /app/assets/static
RUN if [ -d "/app/assets/${ECOSYSTEM}" ]; then \
        cp -r /app/assets/${ECOSYSTEM}/. /app/assets/static/; \
    fi

CMD pm2-runtime start ecosystem.config.js --env ${ECOSYSTEM}
