services:
  portal:
    container_name: portal
    build:
      context: .
      dockerfile: Dockerfile.portal
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - PORT=${PORT:-3000}
    image: portal:latest
    expose:
      - "${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
    networks:
      - netlab01
    volumes:
      - $PWD/config:/portal/site01/config
      - portaldata:/app/assets/static/core/uploads

volumes:
  portaldata:
    name: portaldata
    external: true

networks:
  netlab01:
    external: true
