FROM node:18.20.4-alpine3.19

EXPOSE 3003

RUN adduser -u 1006 portal -D

WORKDIR /app

COPY package*.json .

RUN npm i pm2 -g

COPY . .

RUN chown -R portal:portal /app

USER portal

RUN npm i
RUN ln -s /app/assets/drone /app/assets/static
RUN mkdir -p /app/assets/static/core/uploads/Archive

CMD [ "pm2-runtime", "start", "ecosystem.config.js", "--env", "drone" ]
