services:
  ceds:
    container_name: ceds
    build:
      context: .
      dockerfile: Dockerfile.portal
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
        - PORT=${PORT:-3000}
        - ECOSYSTEM=${ECOSYSTEM:-portal}
    image: ceds:latest
    expose:
      - "${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
    networks:
      - netlab01
    volumes:
      - $PWD/config:/ceds/site01/config
      - cedsdata:/app/assets/static/core/uploads

volumes:
  cedsdata:
    name: cedsdata
    external: true

networks:
  netlab01:
    external: true
