server {
        listen 80;
        listen [::]:80;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name drone-comp.ita.br www.drone-comp.ita.br;
	client_max_body_size 2048M;
        location / {
                proxy_pass http://drone:3003;
        }
        location ~ /.well-known/acme-challenge {
                allow all;
                root /var/www/html;
        }
}
